# Generated by Django 5.2.1 on 2025-05-18 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
